version: '3'

services:
  mail:
    image: tvial/docker-mailserver:2.3
    hostname: mail
    domainname: enzado.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /var/www/html/enzado.com/cert:/tmp/ssl:ro
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - OVERRIDE_HOSTNAME=mail.enzado.com
    - POSTMASTER_ADDRESS=postmaster@enzado.com
    cap_add:
    - NET_ADMIN
    restart: always

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
